In [18]:
import numpy as np
x = np.array([[1, 2, 3], [4, 5, 6]])
print ("x:\n{}".format(x))

x:
[[1 2 3]
 [4 5 6]]


In [16]:
from scipy import sparse

eye = np.eye(4)
print ("NumPy array:\n{}".format(eye))

NumPy array:
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]


In [19]:
sparse_matrix = sparse.csr_matrix(eye)
print ("\nSciPy sparse CSR matrix:\n{}".format(sparse_matrix))


SciPy sparse CSR matrix:
  (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 3)	1.0
